#haig-fras-versioning/mbtiles/habitats_new-65536.mbtiles
echo "POSTGRES_USER=$POSTGRES_USER
POSTGRES_PASSWORD=$POSTGRES_PASSWORD
POSTGRES_DB=$POSTGRES_DB
POSTGRES_PORT=$POSTGRES_PORT
POSTGRES_HOST=$POSTGRES_HOST
REDIS_HOST=$REDIS_HOST
REDIS_PORT=$REDIS_PORT" > .env


echo "POSTGRES_USER=$POSTGRES_USER
POSTGRES_PASSWORD=$POSTGRES_PASSWORD
POSTGRES_DB=$POSTGRES_DB
POSTGRES_PORT=$POSTGRES_PORT
POSTGRES_HOST=${POSTGRES_HOST}-dev
REDIS_HOST=$REDIS_HOST
REDIS_PORT=$REDIS_PORT" > .env.staging
