#!/bin/bash

cat <<EOF > .env
POSTGRES_USER=${POSTGRES_USER}
POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
POSTGRES_DB=${POSTGRES_DB}
POSTGRES_PORT=${POSTGRES_PORT}
POSTGRES_HOST=${POSTGRES_HOST}
REDIS_HOST=${REDIS_HOST}
REDIS_PORT=${REDIS_PORT}
POSTGRES_PORT_ALEMBIC=${POSTGRES_PORT}
POSTGRES_HOST_ALEMBIC=${POSTGRES_HOST}
EOF
