"""Correct uncertainty meters name

Revision ID: fa47b954cbea
Revises: 711062643a39
Create Date: 2025-08-12 22:21:26.481053

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fa47b954cbea'
down_revision: Union[str, Sequence[str], None] = '711062643a39'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('images', 'dataset_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_constraint(op.f('images_dataset_id_fkey'), 'images', type_='foreignkey')
    op.create_foreign_key(None, 'images', 'datasets', ['dataset_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'images', type_='foreignkey')
    op.create_foreign_key(op.f('images_dataset_id_fkey'), 'images', 'datasets', ['dataset_id'], ['id'], onupdate='CASCADE', ondelete='SET NULL')
    op.alter_column('images', 'dataset_id',
               existing_type=sa.UUID(),
               nullable=True)
    # ### end Alembic commands ###
