"""Correct uncertainty meters name

Revision ID: 711062643a39
Revises: 71cfa914a0e5
Create Date: 2025-08-12 15:25:57.545520

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '711062643a39'
down_revision: Union[str, Sequence[str], None] = '71cfa914a0e5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('datasets', sa.Column('coordinate_uncertainty_meters', sa.Float(), nullable=True))
    op.drop_column('datasets', 'coordinate_uncertainty_m')
    op.add_column('images', sa.Column('coordinate_uncertainty_meters', sa.Float(), nullable=True))
    op.drop_column('images', 'coordinate_uncertainty_m')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('images', sa.Column('coordinate_uncertainty_m', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.drop_column('images', 'coordinate_uncertainty_meters')
    op.add_column('datasets', sa.Column('coordinate_uncertainty_m', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.drop_column('datasets', 'coordinate_uncertainty_meters')
    # ### end Alembic commands ###
