"""Add labels source

Revision ID: 698a2871c1f2
Revises: fa47b954cbea
Create Date: 2026-01-22 13:00:32.014732

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '698a2871c1f2'
down_revision: Union[str, Sequence[str], None] = 'fa47b954cbea'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('label_sources',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.add_column('labels', sa.Column('parent_id', sa.UUID(), nullable=True))
    op.add_column('labels', sa.Column('label_source_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'labels', 'label_sources', ['label_source_id'], ['id'])
    op.create_foreign_key(None, 'labels', 'labels', ['parent_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'labels', type_='foreignkey')
    op.drop_constraint(None, 'labels', type_='foreignkey')
    op.drop_column('labels', 'label_source_id')
    op.drop_column('labels', 'parent_id')
    op.drop_table('label_sources')
    # ### end Alembic commands ###
