"""Update models

Revision ID: 96dba640cbc1
Revises: 37fd04ed36d4
Create Date: 2026-02-02 12:37:46.217525

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '96dba640cbc1'
down_revision: Union[str, Sequence[str], None] = '37fd04ed36d4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('annotations', sa.Column('dimension_pixels', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('annotations', 'dimension_pixels')
    # ### end Alembic commands ###
