"""Update models

Revision ID: 37fd04ed36d4
Revises: c63e4d316b88
Create Date: 2026-02-02 12:07:40.666093

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '37fd04ed36d4'
down_revision: Union[str, Sequence[str], None] = 'c63e4d316b88'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'annotation_labels', ['id'])
    op.create_unique_constraint(None, 'annotation_sets', ['id'])
    op.create_unique_constraint(None, 'annotations', ['id'])
    op.create_unique_constraint(None, 'annotators', ['id'])
    op.create_unique_constraint(None, 'contexts', ['id'])
    op.create_unique_constraint(None, 'creators', ['id'])
    op.create_unique_constraint(None, 'events', ['id'])
    op.create_unique_constraint(None, 'image_camera_calibration_models', ['id'])
    op.create_unique_constraint(None, 'image_camera_housing_viewports', ['id'])
    op.create_unique_constraint(None, 'image_camera_poses', ['id'])
    op.create_unique_constraint(None, 'image_domeport_parameters', ['id'])
    op.create_unique_constraint(None, 'image_flatport_parameters', ['id'])
    op.create_unique_constraint(None, 'image_photometric_calibrations', ['id'])
    op.create_unique_constraint(None, 'image_sets', ['id'])
    op.create_unique_constraint(None, 'images', ['id'])
    op.create_unique_constraint(None, 'labels', ['id'])
    op.create_unique_constraint(None, 'licenses', ['id'])
    op.create_unique_constraint(None, 'pis', ['id'])
    op.create_unique_constraint(None, 'platforms', ['id'])
    op.create_unique_constraint(None, 'projects', ['id'])
    op.create_unique_constraint(None, 'related_materials', ['id'])
    op.create_unique_constraint(None, 'sensors', ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'sensors', type_='unique')
    op.drop_constraint(None, 'related_materials', type_='unique')
    op.drop_constraint(None, 'projects', type_='unique')
    op.drop_constraint(None, 'platforms', type_='unique')
    op.drop_constraint(None, 'pis', type_='unique')
    op.drop_constraint(None, 'licenses', type_='unique')
    op.drop_constraint(None, 'labels', type_='unique')
    op.drop_constraint(None, 'images', type_='unique')
    op.drop_constraint(None, 'image_sets', type_='unique')
    op.drop_constraint(None, 'image_photometric_calibrations', type_='unique')
    op.drop_constraint(None, 'image_flatport_parameters', type_='unique')
    op.drop_constraint(None, 'image_domeport_parameters', type_='unique')
    op.drop_constraint(None, 'image_camera_poses', type_='unique')
    op.drop_constraint(None, 'image_camera_housing_viewports', type_='unique')
    op.drop_constraint(None, 'image_camera_calibration_models', type_='unique')
    op.drop_constraint(None, 'events', type_='unique')
    op.drop_constraint(None, 'creators', type_='unique')
    op.drop_constraint(None, 'contexts', type_='unique')
    op.drop_constraint(None, 'annotators', type_='unique')
    op.drop_constraint(None, 'annotations', type_='unique')
    op.drop_constraint(None, 'annotation_sets', type_='unique')
    op.drop_constraint(None, 'annotation_labels', type_='unique')
    # ### end Alembic commands ###
