"""Initial Migration

Revision ID: a463af83af28
Revises: edf8a2627a2a
Create Date: 2026-01-27 17:08:04.478064

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a463af83af28'
down_revision: Union[str, Sequence[str], None] = 'edf8a2627a2a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('annotation_labels', 'confidence')
    op.add_column('labels', sa.Column('parent_label_name', sa.String(length=255), nullable=False))
    op.alter_column('labels', 'annotation_set_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_column('labels', 'group')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('labels', sa.Column('group', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.alter_column('labels', 'annotation_set_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_column('labels', 'parent_label_name')
    op.add_column('annotation_labels', sa.Column('confidence', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
