"""Your message here

Revision ID: c63e4d316b88
Revises: 
Create Date: 2026-02-02 11:41:58.364643

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from geoalchemy2 import Geometry
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c63e4d316b88'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('annotators',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('contexts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('uri', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('creators',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('uri', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('uri', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('image_camera_calibration_models',
    sa.Column('calibration_model_type', sa.String(length=100), nullable=True),
    sa.Column('focal_length_xy_pixel', postgresql.ARRAY(sa.Float(), dimensions=1), nullable=True),
    sa.Column('principal_point_xy_pixel', postgresql.ARRAY(sa.Float(), dimensions=1), nullable=True),
    sa.Column('distortion_coefficients', postgresql.ARRAY(sa.Float(), dimensions=1), nullable=True),
    sa.Column('approximate_field_of_view_water_xy_degree', postgresql.ARRAY(sa.Float(), dimensions=1), nullable=True),
    sa.Column('extra_description', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('image_camera_housing_viewports',
    sa.Column('viewport_type', sa.String(length=100), nullable=True),
    sa.Column('optical_density', sa.Float(), nullable=True),
    sa.Column('thickness_millimeters', sa.Float(), nullable=True),
    sa.Column('extra_description', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('image_camera_poses',
    sa.Column('utm_zone', sa.String(length=10), nullable=True),
    sa.Column('utm_epsg', sa.String(length=10), nullable=True),
    sa.Column('utm_east_north_up_meters', postgresql.ARRAY(sa.Float(), dimensions=1), nullable=True),
    sa.Column('absolute_orientation_utm_matrix', postgresql.ARRAY(sa.Float(), dimensions=1), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('image_domeport_parameters',
    sa.Column('outer_radius_millimeters', sa.Float(), nullable=True),
    sa.Column('decentering_offset_xyz_millimeters', postgresql.ARRAY(sa.Float(), dimensions=1), nullable=True),
    sa.Column('extra_description', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('image_flatport_parameters',
    sa.Column('lens_port_distance_millimeters', sa.Float(), nullable=True),
    sa.Column('interface_normal_direction', postgresql.ARRAY(sa.Float(), dimensions=1), nullable=True),
    sa.Column('extra_description', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('image_photometric_calibrations',
    sa.Column('sequence_white_balancing', sa.Text(), nullable=True),
    sa.Column('exposure_factor_rgb', postgresql.ARRAY(sa.Float(), dimensions=1), nullable=True),
    sa.Column('sequence_illumination_type', sa.String(length=100), nullable=True),
    sa.Column('sequence_illumination_description', sa.Text(), nullable=True),
    sa.Column('illumination_factor_rgb', postgresql.ARRAY(sa.Float(), dimensions=1), nullable=True),
    sa.Column('water_properties_description', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('licenses',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('uri', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('pis',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('uri', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('platforms',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('uri', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('projects',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('uri', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('related_materials',
    sa.Column('uri', sa.String(), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('relation', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('sensors',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('uri', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('annotation_sets',
    sa.Column('context_id', sa.UUID(), nullable=True),
    sa.Column('project_id', sa.UUID(), nullable=True),
    sa.Column('pi_id', sa.UUID(), nullable=True),
    sa.Column('license_id', sa.UUID(), nullable=True),
    sa.Column('version', sa.String(length=50), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('handle', sa.String(), nullable=True),
    sa.Column('copyright', sa.String(length=500), nullable=True),
    sa.Column('abstract', sa.Text(), nullable=True),
    sa.Column('objective', sa.Text(), nullable=True),
    sa.Column('target_environment', sa.Text(), nullable=True),
    sa.Column('target_timescale', sa.Text(), nullable=True),
    sa.Column('curation_protocol', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['context_id'], ['contexts.id'], onupdate='CASCADE', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['license_id'], ['licenses.id'], onupdate='CASCADE', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['pi_id'], ['pis.id'], onupdate='CASCADE', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], onupdate='CASCADE', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_geospatial_table('image_sets',
    sa.Column('context_id', sa.UUID(), nullable=True),
    sa.Column('project_id', sa.UUID(), nullable=True),
    sa.Column('event_id', sa.UUID(), nullable=True),
    sa.Column('platform_id', sa.UUID(), nullable=True),
    sa.Column('sensor_id', sa.UUID(), nullable=True),
    sa.Column('pi_id', sa.UUID(), nullable=True),
    sa.Column('license_id', sa.UUID(), nullable=True),
    sa.Column('camera_pose_id', sa.UUID(), nullable=True),
    sa.Column('camera_housing_viewport_id', sa.UUID(), nullable=True),
    sa.Column('flatport_parameter_id', sa.UUID(), nullable=True),
    sa.Column('domeport_parameter_id', sa.UUID(), nullable=True),
    sa.Column('photometric_calibration_id', sa.UUID(), nullable=True),
    sa.Column('camera_calibration_model_id', sa.UUID(), nullable=True),
    sa.Column('local_path', sa.String(length=500), nullable=True),
    sa.Column('min_latitude_degrees', sa.Float(), nullable=True),
    sa.Column('max_latitude_degrees', sa.Float(), nullable=True),
    sa.Column('min_longitude_degrees', sa.Float(), nullable=True),
    sa.Column('max_longitude_degrees', sa.Float(), nullable=True),
    sa.Column('limits', Geometry(geometry_type='POLYGON', srid=4326, spatial_index=False, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('handle', sa.String(), nullable=True),
    sa.Column('copyright', sa.String(length=500), nullable=True),
    sa.Column('abstract', sa.Text(), nullable=True),
    sa.Column('objective', sa.Text(), nullable=True),
    sa.Column('target_environment', sa.Text(), nullable=True),
    sa.Column('target_timescale', sa.Text(), nullable=True),
    sa.Column('curation_protocol', sa.Text(), nullable=True),
    sa.Column('sha256_hash', sa.String(length=64), nullable=True),
    sa.Column('date_time', sa.DateTime(), nullable=True),
    sa.Column('geom', Geometry(geometry_type='POINT', srid=4326, spatial_index=False, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('altitude_meters', sa.Float(), nullable=True),
    sa.Column('coordinate_uncertainty_meters', sa.Float(), nullable=True),
    sa.Column('entropy', sa.Float(), nullable=True),
    sa.Column('particle_count', sa.Integer(), nullable=True),
    sa.Column('average_color', postgresql.ARRAY(sa.Float()), nullable=True),
    sa.Column('mpeg7_color_layout', postgresql.ARRAY(sa.Float()), nullable=True),
    sa.Column('mpeg7_color_statistic', postgresql.ARRAY(sa.Float()), nullable=True),
    sa.Column('mpeg7_color_structure', postgresql.ARRAY(sa.Float()), nullable=True),
    sa.Column('mpeg7_dominant_color', postgresql.ARRAY(sa.Float()), nullable=True),
    sa.Column('mpeg7_edge_histogram', postgresql.ARRAY(sa.Float()), nullable=True),
    sa.Column('mpeg7_homogeneous_texture', postgresql.ARRAY(sa.Float()), nullable=True),
    sa.Column('mpeg7_scalable_color', postgresql.ARRAY(sa.Float()), nullable=True),
    sa.Column('acquisition', sa.Enum('photo', 'video', 'slide', name='acquisitionenum'), nullable=True),
    sa.Column('quality', sa.Enum('raw', 'processed', 'product', name='qualityenum'), nullable=True),
    sa.Column('deployment', sa.Enum('mapping', 'stationary', 'survey', 'exploration', 'experiment', 'sampling', name='deploymentenum'), nullable=True),
    sa.Column('navigation', sa.Enum('satellite', 'beacon', 'transponder', 'reconstructed', name='navigationenum'), nullable=True),
    sa.Column('scale_reference', sa.Enum('camera_3d', 'camera_calibrated', 'laser_marker', 'optical_flow', name='scalereferenceenum'), nullable=True),
    sa.Column('illumination', sa.Enum('sunlight', 'artificial_light', 'mixed_light', name='illuminationenum'), nullable=True),
    sa.Column('pixel_magnitude', sa.Enum('km', 'hm', 'dam', 'm', 'cm', 'mm', 'um', name='pixelmagnitudeenum'), nullable=True),
    sa.Column('marine_zone', sa.Enum('seafloor', 'water_column', 'sea_surface', 'atmosphere', 'laboratory', name='marinezoneenum'), nullable=True),
    sa.Column('spectral_resolution', sa.Enum('grayscale', 'rgb', 'multi_spectral', 'hyper_spectral', name='spectralresenum'), nullable=True),
    sa.Column('capture_mode', sa.Enum('timer', 'manual', 'mixed', name='capturemodeenum'), nullable=True),
    sa.Column('fauna_attraction', sa.Enum('none', 'baited', 'light', name='faunaattractionenum'), nullable=True),
    sa.Column('area_square_meters', sa.Float(), nullable=True),
    sa.Column('meters_above_ground', sa.Float(), nullable=True),
    sa.Column('acquisition_settings', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('camera_yaw_degrees', sa.Float(), nullable=True),
    sa.Column('camera_pitch_degrees', sa.Float(), nullable=True),
    sa.Column('camera_roll_degrees', sa.Float(), nullable=True),
    sa.Column('overlap_fraction', sa.Float(), nullable=True),
    sa.Column('spatial_constraints', sa.Text(), nullable=True),
    sa.Column('temporal_constraints', sa.Text(), nullable=True),
    sa.Column('time_synchronisation', sa.Text(), nullable=True),
    sa.Column('item_identification_scheme', sa.Text(), nullable=True),
    sa.Column('visual_constraints', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['camera_calibration_model_id'], ['image_camera_calibration_models.id'], ),
    sa.ForeignKeyConstraint(['camera_housing_viewport_id'], ['image_camera_housing_viewports.id'], ),
    sa.ForeignKeyConstraint(['camera_pose_id'], ['image_camera_poses.id'], ),
    sa.ForeignKeyConstraint(['context_id'], ['contexts.id'], onupdate='CASCADE', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['domeport_parameter_id'], ['image_domeport_parameters.id'], ),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], onupdate='CASCADE', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['flatport_parameter_id'], ['image_flatport_parameters.id'], ),
    sa.ForeignKeyConstraint(['license_id'], ['licenses.id'], onupdate='CASCADE', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['photometric_calibration_id'], ['image_photometric_calibrations.id'], ),
    sa.ForeignKeyConstraint(['pi_id'], ['pis.id'], onupdate='CASCADE', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['platform_id'], ['platforms.id'], onupdate='CASCADE', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], onupdate='CASCADE', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['sensor_id'], ['sensors.id'], onupdate='CASCADE', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('sha256_hash')
    )
    op.create_geospatial_index('idx_image_sets_geom', 'image_sets', ['geom'], unique=False, postgresql_using='gist', postgresql_ops={})
    op.create_geospatial_index('idx_image_sets_limits', 'image_sets', ['limits'], unique=False, postgresql_using='gist', postgresql_ops={})
    op.create_table('annotation_set_creators',
    sa.Column('annotation_set_id', sa.UUID(), nullable=False),
    sa.Column('creator_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['annotation_set_id'], ['annotation_sets.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['creator_id'], ['creators.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('annotation_set_id', 'creator_id')
    )
    op.create_table('annotation_set_image_sets',
    sa.Column('annotation_set_id', sa.UUID(), nullable=False),
    sa.Column('image_set_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['annotation_set_id'], ['annotation_sets.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['image_set_id'], ['image_sets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('annotation_set_id', 'image_set_id')
    )
    op.create_table('image_set_creators',
    sa.Column('image_set_id', sa.UUID(), nullable=False),
    sa.Column('creator_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['creator_id'], ['creators.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['image_set_id'], ['image_sets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('image_set_id', 'creator_id')
    )
    op.create_table('image_set_related_materials',
    sa.Column('image_set_id', sa.UUID(), nullable=False),
    sa.Column('material_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['image_set_id'], ['image_sets.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['material_id'], ['related_materials.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('image_set_id', 'material_id')
    )
    op.create_geospatial_table('images',
    sa.Column('context_id', sa.UUID(), nullable=True),
    sa.Column('project_id', sa.UUID(), nullable=True),
    sa.Column('event_id', sa.UUID(), nullable=True),
    sa.Column('platform_id', sa.UUID(), nullable=True),
    sa.Column('sensor_id', sa.UUID(), nullable=True),
    sa.Column('pi_id', sa.UUID(), nullable=True),
    sa.Column('license_id', sa.UUID(), nullable=True),
    sa.Column('camera_pose_id', sa.UUID(), nullable=True),
    sa.Column('camera_housing_viewport_id', sa.UUID(), nullable=True),
    sa.Column('flatport_parameter_id', sa.UUID(), nullable=True),
    sa.Column('domeport_parameter_id', sa.UUID(), nullable=True),
    sa.Column('photometric_calibration_id', sa.UUID(), nullable=True),
    sa.Column('camera_calibration_model_id', sa.UUID(), nullable=True),
    sa.Column('image_set_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('handle', sa.String(), nullable=True),
    sa.Column('copyright', sa.String(length=500), nullable=True),
    sa.Column('abstract', sa.Text(), nullable=True),
    sa.Column('objective', sa.Text(), nullable=True),
    sa.Column('target_environment', sa.Text(), nullable=True),
    sa.Column('target_timescale', sa.Text(), nullable=True),
    sa.Column('curation_protocol', sa.Text(), nullable=True),
    sa.Column('sha256_hash', sa.String(length=64), nullable=True),
    sa.Column('date_time', sa.DateTime(), nullable=True),
    sa.Column('geom', Geometry(geometry_type='POINT', srid=4326, spatial_index=False, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('altitude_meters', sa.Float(), nullable=True),
    sa.Column('coordinate_uncertainty_meters', sa.Float(), nullable=True),
    sa.Column('entropy', sa.Float(), nullable=True),
    sa.Column('particle_count', sa.Integer(), nullable=True),
    sa.Column('average_color', postgresql.ARRAY(sa.Float()), nullable=True),
    sa.Column('mpeg7_color_layout', postgresql.ARRAY(sa.Float()), nullable=True),
    sa.Column('mpeg7_color_statistic', postgresql.ARRAY(sa.Float()), nullable=True),
    sa.Column('mpeg7_color_structure', postgresql.ARRAY(sa.Float()), nullable=True),
    sa.Column('mpeg7_dominant_color', postgresql.ARRAY(sa.Float()), nullable=True),
    sa.Column('mpeg7_edge_histogram', postgresql.ARRAY(sa.Float()), nullable=True),
    sa.Column('mpeg7_homogeneous_texture', postgresql.ARRAY(sa.Float()), nullable=True),
    sa.Column('mpeg7_scalable_color', postgresql.ARRAY(sa.Float()), nullable=True),
    sa.Column('acquisition', sa.Enum('photo', 'video', 'slide', name='acquisitionenum'), nullable=True),
    sa.Column('quality', sa.Enum('raw', 'processed', 'product', name='qualityenum'), nullable=True),
    sa.Column('deployment', sa.Enum('mapping', 'stationary', 'survey', 'exploration', 'experiment', 'sampling', name='deploymentenum'), nullable=True),
    sa.Column('navigation', sa.Enum('satellite', 'beacon', 'transponder', 'reconstructed', name='navigationenum'), nullable=True),
    sa.Column('scale_reference', sa.Enum('camera_3d', 'camera_calibrated', 'laser_marker', 'optical_flow', name='scalereferenceenum'), nullable=True),
    sa.Column('illumination', sa.Enum('sunlight', 'artificial_light', 'mixed_light', name='illuminationenum'), nullable=True),
    sa.Column('pixel_magnitude', sa.Enum('km', 'hm', 'dam', 'm', 'cm', 'mm', 'um', name='pixelmagnitudeenum'), nullable=True),
    sa.Column('marine_zone', sa.Enum('seafloor', 'water_column', 'sea_surface', 'atmosphere', 'laboratory', name='marinezoneenum'), nullable=True),
    sa.Column('spectral_resolution', sa.Enum('grayscale', 'rgb', 'multi_spectral', 'hyper_spectral', name='spectralresenum'), nullable=True),
    sa.Column('capture_mode', sa.Enum('timer', 'manual', 'mixed', name='capturemodeenum'), nullable=True),
    sa.Column('fauna_attraction', sa.Enum('none', 'baited', 'light', name='faunaattractionenum'), nullable=True),
    sa.Column('area_square_meters', sa.Float(), nullable=True),
    sa.Column('meters_above_ground', sa.Float(), nullable=True),
    sa.Column('acquisition_settings', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('camera_yaw_degrees', sa.Float(), nullable=True),
    sa.Column('camera_pitch_degrees', sa.Float(), nullable=True),
    sa.Column('camera_roll_degrees', sa.Float(), nullable=True),
    sa.Column('overlap_fraction', sa.Float(), nullable=True),
    sa.Column('spatial_constraints', sa.Text(), nullable=True),
    sa.Column('temporal_constraints', sa.Text(), nullable=True),
    sa.Column('time_synchronisation', sa.Text(), nullable=True),
    sa.Column('item_identification_scheme', sa.Text(), nullable=True),
    sa.Column('visual_constraints', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['camera_calibration_model_id'], ['image_camera_calibration_models.id'], ),
    sa.ForeignKeyConstraint(['camera_housing_viewport_id'], ['image_camera_housing_viewports.id'], ),
    sa.ForeignKeyConstraint(['camera_pose_id'], ['image_camera_poses.id'], ),
    sa.ForeignKeyConstraint(['context_id'], ['contexts.id'], onupdate='CASCADE', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['domeport_parameter_id'], ['image_domeport_parameters.id'], ),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], onupdate='CASCADE', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['flatport_parameter_id'], ['image_flatport_parameters.id'], ),
    sa.ForeignKeyConstraint(['image_set_id'], ['image_sets.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['license_id'], ['licenses.id'], onupdate='CASCADE', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['photometric_calibration_id'], ['image_photometric_calibrations.id'], ),
    sa.ForeignKeyConstraint(['pi_id'], ['pis.id'], onupdate='CASCADE', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['platform_id'], ['platforms.id'], onupdate='CASCADE', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], onupdate='CASCADE', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['sensor_id'], ['sensors.id'], onupdate='CASCADE', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('sha256_hash')
    )
    op.create_geospatial_index('idx_images_geom', 'images', ['geom'], unique=False, postgresql_using='gist', postgresql_ops={})
    op.create_table('labels',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('parent_label_name', sa.String(length=255), nullable=False),
    sa.Column('lowest_taxonomic_name', sa.String(length=255), nullable=True),
    sa.Column('lowest_aphia_id', sa.String(length=50), nullable=True),
    sa.Column('name_is_lowest', sa.Boolean(), nullable=False),
    sa.Column('identification_qualifier', sa.String(length=255), nullable=True),
    sa.Column('annotation_set_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['annotation_set_id'], ['annotation_sets.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('annotations',
    sa.Column('image_id', sa.UUID(), nullable=False),
    sa.Column('annotation_platform', sa.String(length=255), nullable=True),
    sa.Column('shape', sa.Enum('single_pixel', 'polyline', 'polygon', 'circle', 'rectangle', 'ellipse', 'whole_image', name='shapeenum'), nullable=False),
    sa.Column('coordinates', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('annotation_set_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['annotation_set_id'], ['annotation_sets.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['image_id'], ['images.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('image_creators',
    sa.Column('image_id', sa.UUID(), nullable=False),
    sa.Column('creator_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['creator_id'], ['creators.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['image_id'], ['images.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('image_id', 'creator_id')
    )
    op.create_table('annotation_labels',
    sa.Column('label_id', sa.UUID(), nullable=False),
    sa.Column('annotation_id', sa.UUID(), nullable=False),
    sa.Column('annotator_id', sa.UUID(), nullable=True),
    sa.Column('creation_datetime', sa.String(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['annotation_id'], ['annotations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['annotator_id'], ['annotators.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['label_id'], ['labels.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('annotation_labels')
    op.drop_table('image_creators')
    op.drop_table('annotations')
    op.drop_table('labels')
    op.drop_geospatial_index('idx_images_geom', table_name='images', postgresql_using='gist', column_name='geom')
    op.drop_geospatial_table('images')
    op.drop_table('image_set_related_materials')
    op.drop_table('image_set_creators')
    op.drop_table('annotation_set_image_sets')
    op.drop_table('annotation_set_creators')
    op.drop_geospatial_index('idx_image_sets_limits', table_name='image_sets', postgresql_using='gist', column_name='limits')
    op.drop_geospatial_index('idx_image_sets_geom', table_name='image_sets', postgresql_using='gist', column_name='geom')
    op.drop_geospatial_table('image_sets')
    op.drop_table('annotation_sets')
    op.drop_table('sensors')
    op.drop_table('related_materials')
    op.drop_table('projects')
    op.drop_table('platforms')
    op.drop_table('pis')
    op.drop_table('licenses')
    op.drop_table('image_photometric_calibrations')
    op.drop_table('image_flatport_parameters')
    op.drop_table('image_domeport_parameters')
    op.drop_table('image_camera_poses')
    op.drop_table('image_camera_housing_viewports')
    op.drop_table('image_camera_calibration_models')
    op.drop_table('events')
    op.drop_table('creators')
    op.drop_table('contexts')
    op.drop_table('annotators')
    # ### end Alembic commands ###
