"""Initial Migration

Revision ID: edf8a2627a2a
Revises: deecbda256f6
Create Date: 2026-01-27 16:36:10.265818

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'edf8a2627a2a'
down_revision: Union[str, Sequence[str], None] = 'deecbda256f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('annotation_labels', 'annotator_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.create_unique_constraint(None, 'annotation_labels', ['id'])
    op.add_column('annotation_set_creators', sa.Column('annotation_set_id', sa.UUID(), nullable=False))
    op.drop_constraint(op.f('annotation_set_creators_annotation_id_fkey'), 'annotation_set_creators', type_='foreignkey')
    op.create_foreign_key(None, 'annotation_set_creators', 'annotation_sets', ['annotation_set_id'], ['id'], ondelete='CASCADE')
    op.drop_column('annotation_set_creators', 'annotation_id')
    op.add_column('annotation_set_image_sets', sa.Column('annotation_set_id', sa.UUID(), nullable=False))
    op.drop_constraint(op.f('annotation_set_image_sets_annotation_id_fkey'), 'annotation_set_image_sets', type_='foreignkey')
    op.create_foreign_key(None, 'annotation_set_image_sets', 'annotation_sets', ['annotation_set_id'], ['id'], ondelete='CASCADE')
    op.drop_column('annotation_set_image_sets', 'annotation_id')
    op.create_unique_constraint(None, 'annotation_sets', ['id'])
    op.alter_column('annotations', 'annotation_set_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.create_unique_constraint(None, 'annotations', ['id'])
    op.create_unique_constraint(None, 'annotators', ['id'])
    op.create_unique_constraint(None, 'contexts', ['id'])
    op.create_unique_constraint(None, 'creators', ['id'])
    op.create_unique_constraint(None, 'events', ['id'])
    op.create_unique_constraint(None, 'image_camera_calibration_models', ['id'])
    op.create_unique_constraint(None, 'image_camera_housing_viewports', ['id'])
    op.create_unique_constraint(None, 'image_camera_poses', ['id'])
    op.create_unique_constraint(None, 'image_domeport_parameters', ['id'])
    op.create_unique_constraint(None, 'image_flatport_parameters', ['id'])
    op.create_unique_constraint(None, 'image_photometric_calibrations', ['id'])
    op.create_unique_constraint(None, 'image_sets', ['id'])
    op.create_unique_constraint(None, 'images', ['id'])
    op.create_unique_constraint(None, 'labels', ['id'])
    op.create_unique_constraint(None, 'licenses', ['id'])
    op.create_unique_constraint(None, 'pis', ['id'])
    op.create_unique_constraint(None, 'platforms', ['id'])
    op.create_unique_constraint(None, 'projects', ['id'])
    op.create_unique_constraint(None, 'provenance_activities', ['id'])
    op.create_unique_constraint(None, 'provenance_agents', ['id'])
    op.create_unique_constraint(None, 'provenance_entities', ['id'])
    op.create_unique_constraint(None, 'related_materials', ['id'])
    op.create_unique_constraint(None, 'sensors', ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'sensors', type_='unique')
    op.drop_constraint(None, 'related_materials', type_='unique')
    op.drop_constraint(None, 'provenance_entities', type_='unique')
    op.drop_constraint(None, 'provenance_agents', type_='unique')
    op.drop_constraint(None, 'provenance_activities', type_='unique')
    op.drop_constraint(None, 'projects', type_='unique')
    op.drop_constraint(None, 'platforms', type_='unique')
    op.drop_constraint(None, 'pis', type_='unique')
    op.drop_constraint(None, 'licenses', type_='unique')
    op.drop_constraint(None, 'labels', type_='unique')
    op.drop_constraint(None, 'images', type_='unique')
    op.drop_constraint(None, 'image_sets', type_='unique')
    op.drop_constraint(None, 'image_photometric_calibrations', type_='unique')
    op.drop_constraint(None, 'image_flatport_parameters', type_='unique')
    op.drop_constraint(None, 'image_domeport_parameters', type_='unique')
    op.drop_constraint(None, 'image_camera_poses', type_='unique')
    op.drop_constraint(None, 'image_camera_housing_viewports', type_='unique')
    op.drop_constraint(None, 'image_camera_calibration_models', type_='unique')
    op.drop_constraint(None, 'events', type_='unique')
    op.drop_constraint(None, 'creators', type_='unique')
    op.drop_constraint(None, 'contexts', type_='unique')
    op.drop_constraint(None, 'annotators', type_='unique')
    op.drop_constraint(None, 'annotations', type_='unique')
    op.alter_column('annotations', 'annotation_set_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_constraint(None, 'annotation_sets', type_='unique')
    op.add_column('annotation_set_image_sets', sa.Column('annotation_id', sa.UUID(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'annotation_set_image_sets', type_='foreignkey')
    op.create_foreign_key(op.f('annotation_set_image_sets_annotation_id_fkey'), 'annotation_set_image_sets', 'annotations', ['annotation_id'], ['id'], ondelete='CASCADE')
    op.drop_column('annotation_set_image_sets', 'annotation_set_id')
    op.add_column('annotation_set_creators', sa.Column('annotation_id', sa.UUID(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'annotation_set_creators', type_='foreignkey')
    op.create_foreign_key(op.f('annotation_set_creators_annotation_id_fkey'), 'annotation_set_creators', 'annotations', ['annotation_id'], ['id'], ondelete='CASCADE')
    op.drop_column('annotation_set_creators', 'annotation_set_id')
    op.drop_constraint(None, 'annotation_labels', type_='unique')
    op.alter_column('annotation_labels', 'annotator_id',
               existing_type=sa.UUID(),
               nullable=False)
    # ### end Alembic commands ###
