"""Update unique values

Revision ID: 32e6c2f7a5c3
Revises: 0085dc77c056
Create Date: 2025-07-18 12:25:28.722179

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '32e6c2f7a5c3'
down_revision: Union[str, Sequence[str], None] = '0085dc77c056'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'annotators', ['name'])
    op.create_unique_constraint(None, 'datasets', ['sha256_hash'])
    op.create_unique_constraint(None, 'datasets', ['name'])
    op.alter_column('image_contexts', 'name',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.create_unique_constraint(None, 'image_contexts', ['name'])
    op.alter_column('image_creators', 'name',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.create_unique_constraint(None, 'image_creators', ['name'])
    op.alter_column('image_events', 'name',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.create_unique_constraint(None, 'image_events', ['name'])
    op.alter_column('image_licenses', 'name',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.create_unique_constraint(None, 'image_licenses', ['name'])
    op.alter_column('image_pis', 'name',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.create_unique_constraint(None, 'image_pis', ['name'])
    op.alter_column('image_platforms', 'name',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.create_unique_constraint(None, 'image_platforms', ['name'])
    op.alter_column('image_projects', 'name',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.create_unique_constraint(None, 'image_projects', ['name'])
    op.alter_column('image_sensors', 'name',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.create_unique_constraint(None, 'image_sensors', ['name'])
    op.create_unique_constraint(None, 'images', ['sha256_hash'])
    op.create_unique_constraint(None, 'labels', ['name'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'labels', type_='unique')
    op.drop_constraint(None, 'images', type_='unique')
    op.drop_constraint(None, 'image_sensors', type_='unique')
    op.alter_column('image_sensors', 'name',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.drop_constraint(None, 'image_projects', type_='unique')
    op.alter_column('image_projects', 'name',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.drop_constraint(None, 'image_platforms', type_='unique')
    op.alter_column('image_platforms', 'name',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.drop_constraint(None, 'image_pis', type_='unique')
    op.alter_column('image_pis', 'name',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.drop_constraint(None, 'image_licenses', type_='unique')
    op.alter_column('image_licenses', 'name',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.drop_constraint(None, 'image_events', type_='unique')
    op.alter_column('image_events', 'name',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.drop_constraint(None, 'image_creators', type_='unique')
    op.alter_column('image_creators', 'name',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.drop_constraint(None, 'image_contexts', type_='unique')
    op.alter_column('image_contexts', 'name',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.drop_constraint(None, 'datasets', type_='unique')
    op.drop_constraint(None, 'datasets', type_='unique')
    op.drop_constraint(None, 'annotators', type_='unique')
    # ### end Alembic commands ###
