"""Initial migration

Revision ID: c1a5c9963805
Revises: 32e6c2f7a5c3
Create Date: 2025-08-05 09:30:55.226508

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c1a5c9963805'
down_revision: Union[str, Sequence[str], None] = '32e6c2f7a5c3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('images', sa.Column('name', sa.String(length=255), nullable=False))
    op.create_unique_constraint(None, 'images', ['name'])
    op.drop_column('images', 'local_path')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('images', sa.Column('local_path', sa.VARCHAR(length=500), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'images', type_='unique')
    op.drop_column('images', 'name')
    # ### end Alembic commands ###
