apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "redis-cache.fullname" . }}
  namespace: {{ .Release.Namespace }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "redis-cache.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "redis-cache.name" . }}
    spec:
      containers:
        - name: redis
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          ports:
            - containerPort: {{ .Values.service.port }}
