apiVersion: v1
kind: Service
metadata:
  name: {{ include "redis-cache.fullname" . }}
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    app: {{ include "redis-cache.name" . }}
  ports:
    - name: redis
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
